server:
  port: 80
eureka:
  client:
    register-with-eureka: false
    service-url:
      defaultZone: http://eureka8761.com:8761/eureka, http://eureka8761.com:8761/eureka

ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000