server:
  port: 80


eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaulZone: http://eureka8761.com:8761/eureka,http://eureka8762.com:8762/eureka

spring:
  application:
    name: cloud-consumer-order