server:
  port: 80


eureka:
  client:
    register-with-eureka: true    #表识不向注册中心注册自己
    fetch-registry: true   #表示自己就是注册中心，职责是维护服务实例，并不需要去检索服务
    service-url:
             defaultZone: http://eureka8761.com:8761/eureka/

spring:
  application:
    name: cloud-provider-hystrix-order

ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000